### ISSUE TITLE
Invoice: Safwan Yaseen Parkar

### ISSUE THREAD

**Issue by safwanyp** [opensourcepledge/finances#5]
[SPI-000107.pdf](https://github.com/user-attachments/files/17603372/SPI-000107.pdf)

Please ignore the due date. I have not been able to not specify a due date, and never got around to fiddling with the code to disable it when needed 😭

**Comment by safwanyp** [comment]
Posting another PDF here since it includes names of the customer (Open Source Pledge, Chad Whitacre). Please use whichever one works for you!

[SPI-000107 (new).pdf](https://github.com/user-attachments/files/17608292/SPI-000107.new.pdf)

**Comment by chadwhitacre** [comment]
Thanks @safwanyp. Submitted to Sentry AP.

**Comment by chadwhitacre** [comment]
Future invoices can be sent directly to ap@sentry.io with me cc'd. 🙏

**Comment by safwanyp** [comment]
Appreciate it @chadwhitacre and understood!

**Comment by chadwhitacre** [comment]
BTW for future invoices I recommend filing "Due on receipt," we will pay you faster.

**Comment by safwanyp** [comment]
> BTW for future invoices I recommend filing "Due on receipt," we will pay you faster.

Understood! No issues if you can't give out this info, but without a "Due on receipt" how long does it usually take? Just wanted to get an estimate so I can account for it in my expenses 😁 Again, no biggie if you can't answer that.

**Comment by safwanyp** [comment]
> As late as possible while meeting your expressed due date. In your case that is Jan 1, 2025. 😭

Oh damn 😂 No worries, I'll make sure to keep it in mind next time 😉 
Can i not just recall the invoice an issue a new one though? Have done that before with other people 🤔

**Comment by safwanyp** [comment]
Received the payment on November 18, 2024 at 18:10 CET ✅
